include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/

linter:
  rules:
    - camel_case_types
    - require_trailing_commas
    - avoid_unused_constructor_parameters
    - avoid_multiple_declarations_per_line
    - avoid_print
    - empty_constructor_bodies
    - avoid_empty_else
    - empty_catches
    - avoid_slow_async_io
    - discarded_futures
    - empty_statements
    - use_key_in_widget_constructors
    - use_build_context_synchronously
    - always_put_required_named_parameters_first
    - avoid_escaping_inner_quotes
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - avoid_void_async
    - prefer_const_constructors
    - unnecessary_late
    - use_enums
    - use_named_constants